### ISSUE TITLE
Remove the inserted space before all Line Feeds (LF)

### ISSUE THREAD

**Issue by hao-public** [prolane/samltoawsstskeys#14]
Each line in the credentials-file, has a space inserted before the LF. Please trim before inserting the headers and values into the file. Otherwise, you need to cleanup these spaces, when trying to read the file as an "ini-file".

**Comment by prolane** [comment]
Fixed in release v2.5
https://github.com/prolane/samltoawsstskeys/commit/21f4738cdd9e4e8b13a77973e1f19a12aec6c0f8
