### ISSUE TITLE
Working intermittently after updates a few days ago

### ISSUE THREAD

**Issue by cpollard0** [prolane/samltoawsstskeys#20]
This isn't working 100% of the time now. The credentials file is not getting generated intermittently. 

Using google chrome: Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by prolane** [comment]
Have you tried opting out of the 'SessionDuration' feature in the options panel? Set this setting to 'no' and see if this works for you.

**Comment by cpollard0** [comment]
That did it; thank you sir!
