### ISSUE TITLE
CRLF instead of LF for new line

### ISSUE THREAD

**Issue by allieliongpailui** [prolane/samltoawsstskeys#21]
I am trying to use S3 browser with the credential file but it does not support LF as new line.
The original credentials file using aws configure has CRLF as the new line. 
Can this be changed to CRLF?

**Comment by prolane** [comment]
Fixed in release v2.5
https://github.com/prolane/samltoawsstskeys/commit/21f4738cdd9e4e8b13a77973e1f19a12aec6c0f8
