### ISSUE TITLE
Credentials File Download Issue - Google SessionDuration

### ISSUE THREAD

**Issue by joshphp** [prolane/samltoawsstskeys#22]
We are setting the `SessionDuration` via Google CustomSchema for users logging into AWS via SAML. For some, when they login, the credentials file does not download. To resolve it, they change `Apply the SessionDuration requested by the SAML provider.` to `No` and the file downloads. For others, including myself, it works as expected with that option set to `Yes`. We are running the same version of the plugin (2.3) and the same version of Chrome.

**Comment by prolane** [comment]
The others that need to change the setting to `No`, are they trying to assume the same IAM role as yourself?

Each IAM role has its own maximum session duration setting. Most likely this is the reason why it works for some and doesn't work for others. See also: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use.html#id_roles_use_view-role-max-session

**Comment by joshphp** [comment]
I think I missed updating the duration for a role or two which is then why the credentials file failed to download. Closing!
