### ISSUE TITLE
Chrome 68 breaks credentials download

### ISSUE THREAD

**Issue by hrast01** [prolane/samltoawsstskeys#23]
After the update to Chrome 68, the extension no longer downloads the credentials file when doing SAML auth.  I had a colleague report a problem, and I couldn't reproduce until I updated Chrome, and then I got the same behavior.

**Comment by hrast01** [comment]
Tested that reverting to Chrome 67 did, in fact, resolve the issue.

**Comment by prolane** [comment]
I can't confirm the issue yet.
Tested with Chrome `Version 68.0.3440.84` on Mac and the credentials file downloads without an issue.

Please provide debug logs.
Go to Extensions, turn on 'Developer Mode', and then click 'Inspect views background/background.html' for this extension. This will give you a new window with the console open. Try to use the extension and please share whatever output is generated.

**Comment by hrast01** [comment]
I am also on Mac running High Sierra (10.13.6) and Chrome 68.0.3440.84.  Here's what pops up in the Console in Dev mode.

`Error in event handler for webRequest.onBeforeRequest/1: TypeError: Cannot read property '0' of undefined
    at onBeforeRequestEvent (chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/background/script.js:88:55)`

**Comment by prolane** [comment]
Got it, thanks. I think I see the issue.
Am I right your SAML provider only sends along **one** IAM role?

**Comment by prolane** [comment]
Never mind. I was already able to reproduce myself. The issue is indeed when just one IAM role is present in the SAML claim.

I wonder how this ever worked before Chrome 68. I guess the previous versions were a bit less restrictive to non existing indexes. The issue is in this line of code:
https://github.com/prolane/samltoawsstskeys/blob/e06fcb1e64b8fbf81e02d57c6964e4f10219f9ce/background/script.js#L88

If there is no `roleIndex`, it can't get its value. On line 87 its actually checked if this key exists. But unfortunately on line 88 the value of the key is requested regardless of the existence of the key.

I'll create a fix for it soon.

**Comment by hrast01** [comment]
In my case, I'm only requesting the one role's credentials, but in my colleague's case he was requesting 3 additional role's credentials.

**Comment by hrast01** [comment]
Just for completeness (and my own sense of sanity), I added three additional roles that I can assume to the plugin, same error:

```
Error in event handler for webRequest.onBeforeRequest/1: TypeError: Cannot read property '0' of undefined
    at onBeforeRequestEvent (chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/background/script.js:88:55)
```

**Comment by prolane** [comment]
Thanks for the info, but this still makes sense. The additional roles can only be assumed if the IAM role from the SAML claim can be assumed.

What I was talking about is when your Identity Provider (SAML Provider) adds multiple role claims into the SAML data. 

No worries, I've already made a patch and this seems to work locally. I'll soon push it to the Chrome store.

**Comment by prolane** [comment]
@hrast01 New version is pushed to the Chrome store. Usually its available within 1 hour.
In order for Chrome to fetch the latest version you can best restart Chrome.

**Comment by hrast01** [comment]
Works great, thanks for the quick update!

**Comment by prolane** [comment]
Thanks for letting me know!
