### ISSUE TITLE
Credentials file download fails with GUID filename

### ISSUE THREAD

**Issue by BrandonDusseau** [prolane/samltoawsstskeys#29]
As of this morning, I am no longer able to download the `credentials` file using the extension. Instead of the file, I now get a failed download with a GUID as a filename.

![capture](https://user-images.githubusercontent.com/3901864/52954107-4687ff80-3357-11e9-8fb9-87d1f1114dcd.PNG)

Debug log below:
```
script.js:59 DEBUG: onBeforeRequest event hit!
script.js:79 DEBUG: samlXmlDoc:
script.js:80 [redacted]
script.js:120 ApplySessionDuration: false
script.js:121 SessionDuration: null
script.js:122 hasRoleIndex: true
script.js:123 roleIndex: arn:aws:iam::[redacted]
script.js:161 RoleArn: arn:aws:iam::[redacted]
script.js:162 PrincipalArn: arn:aws:iam::[redacted]:saml-provider/[redacted]
script.js:187 DEBUG: Successfully assumed default profile
script.js:188 docContent:
script.js:189 [default]
aws_access_key_id = [redacted]
aws_secret_access_key = [redacted]
aws_session_token = [redacted]
script.js:195 Generate AWS tokens file.
script.js:261 DEBUG: Now going to download credentials file. Document content:
script.js:262 [default]
aws_access_key_id = [redacted]
aws_secret_access_key = [redacted]
aws_session_token = [redacted]
script.js:266 DEBUG: Blob URL:blob:chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/b7e150af-9f7a-4bf4-88b7-e8a5859511d7
```
Attempting to visit the above URL results in a 404.

Settings:
Filename: credentials
Apply SessionDuration: no
Debug logging: yes
ARN list: none

Running on Chrome version 72.0.3626.81 (updates are disabled by group policy)
Extension version: 2.7

**Comment by prolane** [comment]
Thanks for reporting. This is a known bug in Chrome.
See issue https://github.com/prolane/samltoawsstskeys/issues/28

You need Chrome `72.0.3626.96` or higher.

You could try the workaround mentioned over here if you are unable to upgrade Chrome:
https://github.com/prolane/samltoawsstskeys/issues/28#issuecomment-460381707
