### ISSUE TITLE
Filename ignored

### ISSUE THREAD

**Issue by marky1975** [prolane/samltoawsstskeys#35]
Hi 

Extension works great, however the file name I specify in the options is ignored and instead a random name is generated for the file in the downloads folder from chrome.

Anybody else with this issue?

Thanks

**Comment by AutoMatt-ic** [comment]
This has started happening to me as well.

**Comment by prolane** [comment]
On which version of Chrome are you?
I've updated to the latest version `79.0.3945.117` and for me it still works.

Is there anything strange showing in the logs? 
To see the logs:

Go to Extensions
- Turn on 'Developer Mode'
- Click 'Inspect views background/background.html' for this particular extension
- Go the the 'Console' tab (if its not already active)

**Comment by AutoMatt-ic** [comment]
It was another addon (multi file downloader).  Ripped that out, it behaves as expected.  False alarm.

**Comment by prolane** [comment]
Alright, cool. I'll close the issue then.

**Comment by marky1975** [comment]
Hi

I still have the issue if anyone can help.

**Comment by prolane** [comment]
@marky1975 Did you try what @AutoMatt-ic did? Disable your other Chrome plugins as there is maybe one that interferes?

If thats not the issue, you could also look in the logs (as suggested above) to see if there is anything suspicious.

**Comment by marky1975** [comment]
Hi 

Tried as you suggested and it does look to be and incompatibility with one of the other plugins I have installed,  I have several so its just a case of going through them one by one to see which is the problem. 

Thank you for your help and resolution.

**Comment by prolane** [comment]
Cool. Sure, no worries mate. Glad you like the extension.
