### ISSUE TITLE
FireFox Support: Is current extension on Firefox extensions maintained by this repo/owner?

### ISSUE THREAD

**Issue by ScriptAutomate** [prolane/samltoawsstskeys#53]
Is this supported/maintained for Firefox? If so, what is the extension link, and can it be placed in the README? I can see some in the Firefox extensions that might be this extension, but I want to be certain I'm installing the official one for security purposes.

- https://addons.mozilla.org/en-US/firefox/addon/saml-to-aws-sts-keys/

**Comment by prolane** [comment]
Hi @ScriptAutomate, the FireFox extension uses this repo as source. However, it is uploaded to Mozilla and maintained by someone else. If you have any questions about the FireFox extension, please try to get in touch with. @gbvanrenswoude.

I'll add a note about this in the README for future reference for others.
