### ISSUE TITLE
Download option of credentials stopped working with new version. 

### ISSUE THREAD

**Issue by johnyittiara** [prolane/samltoawsstskeys#63]
Download option of credentials stopped working with new versions - v3.0, v3.1, and v3.2 
Is there any solution for this?

**Comment by prolane** [comment]
Hi @johnyittiara, could you please provide the debug logs?

See here for help:
https://github.com/prolane/samltoawsstskeys#faq-frequently-asked-question

**Comment by jlsangom-seatcode** [comment]
I had the same problem with version 3.0 and 3.1 but with the new version 3.2 it is downloading correctly.

**Comment by prolane** [comment]
Great, thanks for the feedback @jlsangom-seatcode!

**Comment by sanjeevik89** [comment]
@johnyittiara Make sure you have given fileURL access for this extension. You can grant it in mange extension page. 

![image](https://user-images.githubusercontent.com/39965596/208723213-180eb6a5-975b-4eda-b8e4-b80921a339b1.png)

**Comment by johnyittiara** [comment]
> Hi @johnyittiara, could you please provide the debug logs?
> 
> See here for help: https://github.com/prolane/samltoawsstskeys#faq-frequently-asked-question

I cleared the browsing data, clicked on the Update option on the Extensions page, and enabled debug mode. Now download is happening on Chrome. Downloading on MS Edge is still not working.

**Comment by prolane** [comment]
@johnyittiara Thanks for letting me know the extension works for you now.

btw, Chrome should automatically update your extensions in the background, at least during a restart. Perhaps something for you to investigate why this is not happening for you.

I only publish this extension to the Chrome web store. Can't really help you on MS Edge.
