### ISSUE TITLE
Does this chrome extension work?

### ISSUE THREAD

**Issue by etendards** [prolane/samltoawsstskeys#9]
I am not having any success with the latest version of Chrome.  Do I have to run Chrome as Admin or allow the extension some level of access?

**Comment by prolane** [comment]
@etendards Have you been using this Chrome extension before with Okta? Or is this the first time you tried using it? I have never tested it with Okta, but as long as it is SAML it should work.

Could you open the [Chrome DevTools](https://developer.chrome.com/devtools) and check the **Console** tab? Please check if any errors occur.

**Comment by etendards** [comment]
No, I have not got it to work.  I dont see any errors in the Console tab related to this app.  I also have the SAML dev tool extension and can see all of that.

**Comment by etendards** [comment]
I tried incognito and enabled that in the extenstion manager.  Now I get this: 

**credentials.txt Failed - No file
blob:chrome-extension://ekniobabpcnfjgfbphhcolcinmnbehde/4b1a5a79-b7dc-44d1-b126-5e534ae9ac38
Downloaded by SAML to AWS STS Keys Conversion**

I get a popup to save the file.  And I save it.  Then do ctrl+j or look at downloads folder and it isnt updated.

**Comment by prolane** [comment]
The error in incognito mode is quite interesting. I had never tried that, but I just found out I get same error in incognito. So unfortunately this is not related to the issue you are having with Okta. I'll create a new issue for the extension not working in incognito mode.

**Comment by prolane** [comment]
I am actually quite interested in why it doesn't work together with Okta. If I check their website I can start a 30 day trial. I'm not familiar with Okta, but would I be able to set something up myself in Okta without having to connect it to any directory server or anything?

**Comment by prolane** [comment]
Alright, I found [this manual](https://support.okta.com/help/servlet/fileField?retURL=/help/articles/Knowledge_Article/Amazon-Web-Services-and-Okta-Integration-Guide&entityId=ka0F0000000MeyyIAC&field=File_Attachment__Body__s). I'll give this one a try on Thursday and debug what's happening in the extension.

Is what is described in this guide the same as your setup?

**Comment by prolane** [comment]
One other thing you could do is go to the extension tab and tick the box for `Developer mode` at the top. You'll now be able to see this new link at the extension: `Inspect views: background/background.html`. Hit this link, test again, and check if this one shows you any errors.

**Comment by etendards** [comment]
It is working now!  This is great.  I am not sure what changed, maybe clearing cache, or updating the extention.  I have all my profiles setup and it generates API keys for them all.  In Cygwin I created a softlink to the file in my downloads folder.

**Comment by prolane** [comment]
@etendards Great! Glad to hear all is working fine now!
